{
 "title": "eCAL Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hname",
    "query": "SELECT DISTINCT hname FROM processes"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "SELECT DISTINCT tname FROM current_topics"
   },
   {
    "name": "service",
    "query": "SELECT DISTINCT sname FROM current_services"
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Interhost Traffic",
   "type": "nodeGraph",
   "description": "Nodegraph of all currently active hosts and their communication between each other",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT \r\n    arc__ok,\r\n    arc__nok,\r\n    detail__hname,\r\n    detail__hgname,\r\n    detail__ram,\r\n    detail__disk,\r\n    detail__cpu,\r\n    id,\r\n    title,\r\n    subtitle,\r\n    mainstat,\r\n    secondarystat,\r\n    color,\r\n    icon,\r\n    nodeRadius\r\nFROM \r\n    host_nodes;",
     "rawQueryText": "SELECT \r\n    arc__ok,\r\n    arc__nok,\r\n    detail__hname,\r\n    detail__hgname,\r\n    detail__ram,\r\n    detail__disk,\r\n    detail__cpu,\r\n    id,\r\n    title,\r\n    subtitle,\r\n    mainstat,\r\n    secondarystat,\r\n    color,\r\n    icon,\r\n    nodeRadius\r\nFROM \r\n    host_nodes;"
    },
    { "queryText": "SELECT * From host_edges", "rawQueryText": "SELECT * From host_edges" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT * FROM logs\n",
     "rawQueryText": "SELECT * FROM logs\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Message Drops",
   "type": "barchart",
   "description": "Show the 5 subscribers receiving the most message drops.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT hname, tname, direction, message_drops \nFROM current_topics \nWHERE direction = 'subscriber' \nORDER BY message_drops DESC \nLIMIT 5;\n",
     "rawQueryText": "SELECT hname, tname, direction, message_drops \nFROM current_topics \nWHERE direction = 'subscriber' \nORDER BY message_drops DESC \nLIMIT 5;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bandwidth Heatmap",
   "type": "bargauge",
   "description": "Show the 50 processes with the highest network usage in kBps.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT tname, direction, SUM(throughput)\nFROM current_topics\nGROUP BY pid, direction\nORDER BY throughput DESC, tname DESC;",
     "rawQueryText": "SELECT tname, direction, SUM(throughput)\nFROM current_topics\nGROUP BY pid, direction\nORDER BY throughput DESC, tname DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "System Health Monitor",
   "type": "barchart",
   "description": "Shows the process severity of the 5 most severe processes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT uname, state_severity AS \"State Severity\", state_severity_level AS \"State Severity Level\" FROM current_processes\r\nORDER BY state_severity DESC, state_severity_level DESC",
     "rawQueryText": "SELECT uname, state_severity AS \"State Severity\", state_severity_level AS \"State Severity Level\" FROM current_processes\r\nORDER BY state_severity DESC, state_severity_level DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pub Sub Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT direction, COUNT(direction) as count \nFROM current_topics \nGROUP BY direction;",
     "rawQueryText": "SELECT direction, COUNT(direction) as count \nFROM current_topics \nGROUP BY direction;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Communication Layer Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT layer, COUNT(layer) as count \nFROM current_topics \nGROUP BY layer;",
     "rawQueryText": "SELECT layer, COUNT(layer) as count \nFROM current_topics \nGROUP BY layer;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Further Visualizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Pub-Sub Graph for Topic ${topic}",
   "type": "nodeGraph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "repeat": "topic",
   "targets": [
    {
     "queryText": "SELECT * FROM pst_nodes\r\nWHERE secondarystat = 'machine_state_P14SONB058' \r\n",
     "rawQueryText": "SELECT * FROM pst_nodes\r\nWHERE secondarystat = '${topic}' \r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT * FROM pst_edges\r\nWHERE target = 'machine_state_P14SONB058' or source = 'machine_state_P14SONB058'   ",
     "rawQueryText": "SELECT * FROM pst_edges\r\nWHERE target = '${topic}' or source = '${topic}'   ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Client Server",
   "type": "nodeGraph",
   "description": "Nodegraph of a selected service and its clients.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "queryText": "SELECT * FROM cs_nodes\r\nWHERE secondarystat ='DemoService'\r\n",
     "rawQueryText": "SELECT * FROM cs_nodes\r\nWHERE secondarystat ='$service'\r\n"
    },
    {
     "queryText": "SELECT * From cs_edges\r\nWHERE secondarystat ='DemoService'",
     "rawQueryText": "SELECT * From cs_edges\r\nWHERE secondarystat ='$service'"
    }
   ]
  },
  {
   "title": "Process Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "queryText": "SELECT * FROM process_nodes\n",
     "rawQueryText": "SELECT * FROM process_nodes\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT * FROM process_edges\n\n",
     "rawQueryText": "SELECT * FROM process_edges\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Host Overview ${hname}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "hname",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage $hname",
     "type": "gauge",
     "description": "For each host show the percentage of used disk space.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 572 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT \n  hname, \n  (capacity_disk - available_disk) * 100.0 / capacity_disk AS disk_usage_percent\nFROM \n  hosts\nWHERE \n  hname = 'P14SONB058'  \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
       "rawQueryText": "SELECT \n  hname, \n  (capacity_disk - available_disk) * 100.0 / capacity_disk AS disk_usage_percent\nFROM \n  hosts\nWHERE \n  hname = '${hname}'  \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "CPU Usage $hname",
     "type": "gauge",
     "description": "For each host show how much CPU is used (new monitoring param needed)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 572 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT hname, cpu_load\nFROM hosts\nWHERE hname = 'P14SONB058' \nAND time_stamp = (SELECT MAX(time_stamp) FROM hosts WHERE hname = 'P14SONB058')\n\n\n",
       "rawQueryText": "SELECT hname, cpu_load\nFROM hosts\nWHERE hname = '$hname' \nAND time_stamp = (SELECT MAX(time_stamp) FROM hosts WHERE hname = '$hname')\n\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "RAM Usage $hname",
     "type": "gauge",
     "description": "For each host show the percentage of used memory.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 572 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT \n  hname, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = 'P14SONB058' \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
       "rawQueryText": "SELECT \n  hname, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = '$hname' \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "CPU Usage $hname",
     "type": "gauge",
     "description": "For each host show how much CPU is used (new monitoring param needed)",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 672 },
     "repeat": "hname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT hname, cpu_load\nFROM hosts\nWHERE hname = 'P14SONB058' \nAND time_stamp = (SELECT MAX(time_stamp) FROM hosts WHERE hname = 'P14SONB058')\n\n\n",
       "rawQueryText": "SELECT hname, cpu_load\nFROM hosts\nWHERE hname = '$hname' \nAND time_stamp = (SELECT MAX(time_stamp) FROM hosts WHERE hname = '$hname')\n\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "RAM Usage $hname",
     "type": "gauge",
     "description": "For each host show the percentage of used memory.",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 673 },
     "repeat": "hname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT \n  hname, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = 'P14SONB058' \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
       "rawQueryText": "SELECT \n  hname, (total_memory - available_memory) * 100.0 / total_memory AS memory_used\nFROM \n  hosts\nWHERE \n  hname = '$hname' \nORDER BY \n  time_stamp DESC \nLIMIT 1\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Process Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Processes",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2131 },
     "targets": [
      {
       "queryText": "SELECT * FROM current_processes",
       "rawQueryText": "SELECT * FROM current_processes",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Current Topics",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2131 },
     "targets": [
      {
       "queryText": "SELECT * \r\nFROM topics \r\nWHERE time_stamp = (SELECT MAX(time_stamp) FROM topics);\r\n--- Select * from current_topics",
       "rawQueryText": "SELECT * \r\nFROM topics \r\nWHERE time_stamp = (SELECT MAX(time_stamp) FROM topics);\r\n--- Select * from current_topics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Message Drops",
     "type": "table",
     "description": "Show the Publishers/Subscribers that have non-zero message_drops.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2131 },
     "targets": [
      {
       "queryText": "SELECT hname, pid, pname, uname, direction, tname from current_topics\nWHERE message_drops != 0",
       "rawQueryText": "SELECT hname, pid, pname, uname, direction, tname from current_topics\nWHERE message_drops != 0",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Dropped Processes",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2230 },
     "targets": [
      {
       "queryText": "SELECT * FROM dropped_processes",
       "rawQueryText": "SELECT * FROM dropped_processes",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Publisher without Subscriber",
     "type": "table",
     "description": "List publishers that don't have a subscriber connected, either on the same host or on an external host.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2230 },
     "targets": [
      {
       "queryText": "SELECT hname, pid, pname, uname, direction, tname from current_topics\nWHERE connections_ext = 0 AND connections_loc=0 AND direction = 'publisher'\n\n\n\n",
       "rawQueryText": "SELECT hname, pid, pname, uname, direction, tname from current_topics\nWHERE connections_ext = 0 AND connections_loc=0 AND direction = 'publisher'\n\n\n\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Subscriber not receiving data",
     "type": "table",
     "description": "List subscribers that don't have an connection according to connections_loc and connections_ext. Seems odd, that the tsize != 0, another idea would be using directly tsize -> talk to Conti.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2230 },
     "targets": [
      {
       "queryText": "SELECT * from current_topics\nWHERE tsize = 0 AND direction = 'subscriber'",
       "rawQueryText": "SELECT * from current_topics\nWHERE tsize = 0 AND direction = 'subscriber'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Timelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Published Data",
     "type": "timeseries",
     "description": "Monitors total write throughout by the system's publishers in Bit/s (or Bytes/s, whatever tsize of STopicMon returns).",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2132 },
     "targets": [
      {
       "queryText": "SELECT time_stamp, SUM(throughput) \r\nFROM topics \r\nWHERE direction = 'publisher' \r\nGROUP BY time_stamp;\r\n",
       "rawQueryText": "SELECT time_stamp, SUM(throughput) \r\nFROM topics \r\nWHERE direction = 'publisher' \r\nGROUP BY time_stamp;\r\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Global Read Data",
     "type": "timeseries",
     "description": "Monitors total read throughout by the system's subscribers in Bit/s (or Bytes/s, whatever tsize of STopicMon returns).",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2229 },
     "targets": [
      {
       "queryText": "SELECT time_stamp, SUM(throughput) \nFROM topics \nWHERE direction = 'subscriber' \nGROUP BY time_stamp;",
       "rawQueryText": "SELECT time_stamp, SUM(throughput) \nFROM topics \nWHERE direction = 'subscriber' \nGROUP BY time_stamp;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Current Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Processes",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2133 },
     "targets": [
      {
       "queryText": "SELECT * FROM current_processes",
       "rawQueryText": "SELECT * FROM current_processes",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Current Topics",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2133 },
     "targets": [
      {
       "queryText": "SELECT * \r\nFROM topics \r\nWHERE time_stamp = (SELECT MAX(time_stamp) FROM topics);\r\n--- Select * from current_topics",
       "rawQueryText": "SELECT * \r\nFROM topics \r\nWHERE time_stamp = (SELECT MAX(time_stamp) FROM topics);\r\n--- Select * from current_topics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "CurrentServices",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2133 },
     "targets": [
      {
       "queryText": "SELECT * FROM current_services",
       "rawQueryText": "SELECT * FROM current_services",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Previous Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Previous Processes",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2134 },
     "targets": [
      {
       "queryText": "SELECT * FROM previous_processes",
       "rawQueryText": "SELECT * FROM previous_processes",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Previous Topics",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2134 },
     "targets": [
      {
       "queryText": "SELECT * FROM previous_topics",
       "rawQueryText": "SELECT * FROM previous_topics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Previous Services",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2134 },
     "targets": [
      {
       "queryText": "SELECT * FROM previous_services",
       "rawQueryText": "SELECT * FROM previous_services",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2135 },
     "targets": [
      {
       "queryText": "SELECT * FROM processes",
       "rawQueryText": "SELECT * FROM processes",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Topics",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2135 },
     "targets": [
      { "queryText": "SELECT * FROM topics\n", "rawQueryText": "SELECT * FROM topics\n" }
     ]
    },
    {
     "title": "Services",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2135 },
     "targets": [
      {
       "queryText": "SELECT * FROM services",
       "rawQueryText": "SELECT * FROM services",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Dropped Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dropped processes",
     "type": "stat",
     "description": "A list with names and timestamps when a process is shutdown irrespective whether it was graceful or not",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1826 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT uname, time(time_stamp) FROM dropped_processes\nORDER BY time(time_stamp) DESC\n\n\n",
       "rawQueryText": "SELECT uname, time(time_stamp) FROM dropped_processes\nORDER BY time(time_stamp) DESC\n\n\n"
      }
     ]
    }
   ]
  }
 ]
}